In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(
    r'C:\Users\sowja\OneDrive\Desktop\practice_projects\Market_Basket_Optimisation.csv',
    header=None
)

dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
transactions = []

for i in range(0, 7501):
    transactions.append([str(dataset.values[i, j]) for j in range(0, 20)])
df = pd.DataFrame(transactions)

In [ ]:
from pyECLAT import ECLAT

eclat = ECLAT(data=df)
indexes, support = eclat.fit(min_support=0.03, min_combination=2, max_combination=2)

Combination 2 by 2

630it [00:05, 111.09it/s]

In [5]:
print("Frequent Itemsets:")
print(indexes)

Frequent Itemsets:

In [6]:
result_df = pd.DataFrame({
    "Itemset": indexes.keys(),
    "Support": support.values()
})

result_df.sort_values(by="Support", ascending=False)

                              Itemset   Support
10          mineral water & spaghetti  0.059725
11          mineral water & chocolate  0.052660
9                mineral water & eggs  0.050927
0                milk & mineral water  0.047994
5         ground beef & mineral water  0.040928
6             ground beef & spaghetti  0.039195
17              spaghetti & chocolate  0.039195
15                   eggs & spaghetti  0.036528
13                french fries & eggs  0.036395
12  mineral water & frozen vegetables  0.035729
2                    milk & spaghetti  0.035462
14           french fries & chocolate  0.034395
4            pancakes & mineral water  0.033729
8        mineral water & french fries  0.033729
16                   eggs & chocolate  0.033196
3                    milk & chocolate  0.032129
7           mineral water & green tea  0.031063
1                         milk & eggs  0.030796